### PR TITLE
Task watch does not work

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
The task already rolled and is marked as complete and the next change will not find the incomplete task.

```js
var elixir = require('laravel-elixir');
var gulp = require('gulp');

elixir(function(mix){
	mix.sass('app.scss');
});

gulp.task('dev', ['default'], function(){
	gulp.start('watch');
});
```

### CODE REVIEW

**Comment by JeffreyWay** [comment]
You removed a bunch of code that needs to be there. 

What's the problem with task watching not working now? Can you give me a basic example I can try out?

**Comment by ricardogobbosouza** [comment]
If you try to use the above example and run `gulp dev` and change the `app.scss` file while being watching is the error below:

TypeError: Cannot read property 'run' of undefined

**Comment by JeffreyWay** [comment]
Not sure - but this PR would break a bunch of things, so closing for now. 

I can't reproduce when doing `gulp watch`.

**Comment by ricardogobbosouza** [comment]
This happens if you try to use `gulp watch` as a sub task.
Try running `gulp dev` like the example above

**Pull request closed without merging**
