### PR TITLE
Update sass.js

### PR DESCRIPTION
**Pull request by aymenkacem**
Changing the repository path of bootstrap with 'bootstrap-sass' as mentioned in their official documentation

### CODE REVIEW

**Comment by laracasts** [comment]
So, bootstrap-sass-official is no longer a thing?

**Comment by mikeerickson** [comment]
Since when? I am still using as of today?  Hmm?

**Comment by JeffreyWay** [comment]
Going to close this until someone responds with more info.

**Comment by crynobone** [comment]
https://github.com/twbs/bootstrap-sass#c-bower recommends `bower install bootstrap-sass` not `bower install bootstrap-sass-official`.

Also if you do a quick search:

```
$ bower search bootstrap-sass
Search results:

    bootstrap-sass-official git://github.com/twbs/bootstrap-sass.git
    twbs-bootstrap-sass git://github.com/twbs/bootstrap-sass
    bootstrap-sass-twbs git://github.com/twbs/bootstrap-sass.git
    twitter-bootstrap-sass git://github.com/thomas-mcdonald/bootstrap-sass.git
    bootstrap-sass-datepicker git://github.com/abnovak/bootstrap-sass-datepicker.git
    bootstrap-sass git://github.com/twbs/bootstrap-sass.git
    boostrap-sass git://github.com/twbs/bootstrap-sass.git
```

**Pull request closed without merging**
