### PR TITLE
Added an option to Not concatenate the coffeescript files  

### PR DESCRIPTION
**Pull request by fidgetwidget**
this lets those who want it, get the previous behaviour of the coffee call.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Wouldn't you just make multiple calls to .coffee()... no need for another clunky config option.

**Comment by fidgetwidget** [comment]
The previous behaviour allowed for converting entire directories of files, and multiple calls to coffee would not satisfy scenarios where you have 10+ files you want to convert.

**Comment by JeffreyWay** [comment]
This commit will only confuse people, I think. They'll set that config option, and then be confused when it's exclusively used for the coffee() task, and nothing else.

**Comment by fidgetwidget** [comment]
Then are we not going to get a way to have the old behaviour?

**Pull request closed without merging**
