### PR TITLE
fixed coffee, less, sass watching

### PR DESCRIPTION
**Pull request by n7olkachev**

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
This is included in this PR #361

**Comment by JeffreyWay** [comment]
I'm not positive, but I think the call to `prepGulpPaths` needs to go within the anonymous function, like it was before. Is there a specific reason why you moved it up a level?

**Comment by ricardogobbosouza** [comment]
Is a level above to watch the files properly if I change the `src` to a file that is not within the standard configuration `config.get('assets.js.coffee.folder')`, it is not watched

**Comment by n7olkachev** [comment]
Variables in JS are function-scoped, so I couldn't init `paths` in that lambda. It is identical to the `scripts` task.

**Pull request merged**
