### PR TITLE
Change gulp.src to empty string for Tests

### LINKED ISSUE #307: Elixir phpunit does not notify for passed tests
I am building a project using Laravel 5.
I use Gulp and Elixir, and like the notification dialog that tells me the status of my tests.

Now, it is not appearing the Green Test Status dialog (the Red Test Status dialogs is working fine).

I am figuring out why, and I discover that if I remove a test file it works, but if I add one more test it does not work.

For example, If add the following test file, and the Green Test Status dialog does not appear:
```
<?php

class FooTest extends TestCase
{
    public function testFoo()
    {   
      $this->assertTrue(true);
    }   
}
```
Note: Also, the log `"gulp-notify: [PHPUnit Passed] All tests passed!"` does not appear in the console.

I was doing some console.log's inside the file `node_modules/laravel-elixir/Notification.js`, but I could not find why this is happening.

I still cannot fix this problem, so I write my own gulp task for phpunit, but I would like to solve this issue.

OS: Ubuntu 14.04 LTS 64-bit
node: v4.1.2

Link:
http://stackoverflow.com/questions/33060276/elixir-phpunit-does-not-notify-for-passed-tests

### PR DESCRIPTION
**Pull request by parsnick**
Fixes #307, illustrated at [parsnick/elixir-issue-307](https://github.com/parsnick/elixir-issue-307)

Prevents a load of files being sent down the stream unnecessarily. 

The three plugins involved in the test tasks are `gulp-phpunit`, `gulp-phpspec` and `gulp-notify` (with its onLast option). They all ignore the stream's content and only take action on the first (phpunit & phpspec) or the last (notify) file, so this should be a pretty safe change.

### CODE REVIEW

**Comment by parsnick** [comment]
Just for clarification: the empty string in `gulp.src('')` is treated as a relative path, so it resolves to the current working directory.

We need to have something in the stream and it doesn't matter what, as long as it's not empty because then phpunit/phpspec would never get called. The docs for the gulp-php(unit|spec) plugins suggest using phpunit.xml and phpspec.yml as the src, presumably since those files should always exist... but so should the working directory, which works for both plugins.

**Comment by JeffreyWay** [comment]
Two quick notes:

1. I installed your example repo (thanks for that), but the notification did appear in the first example.
2. If you remove the source, that no longer allows the user to override where their tests are located, right?

**Comment by parsnick** [comment]
1. Hmm, that's strange - possibly platform-dependent then, which might explain why it's not affecting more people. I just tried on another machine (but still Ubuntu) and again didn't get the notification. 

2. It shouldn't make any difference - the location of your tests are defined by phpunit.xml / phpspec.yml. In fact, in [gulp-phpunit](https://github.com/mikeerickson/gulp-phpunit/blob/master/index.js#L115) the only thing that the gulp.src (i.e. the `file` argument for that callback) can affect is where it looks for `phpunit.xml`. 

So with this change, all you lose is the ability to do `mix.phpUnit("myOtherPhpunit.xml")` - not sure if that was ever the intended usage anyway. Plus the watcher is unaffected, so you can still do `mix.phpUnit("otherTests/**/*.php")`.

And if you really do want to use a non-standard phpunit.xml path, that's still possible via the `pluginOptions`, i.e. 
```js
mix.phpUnit("files/to/watch.php", { configurationFile: "myOtherPhpunit.xml" })
```

Hope that makes sense!

**Comment by parsnick** [comment]
No longer applicable 5fa4b861a6950479300d5d8883b4ee93760e566a

**Pull request closed without merging**
