### PR TITLE
Add pleeease support

### PR DESCRIPTION
**Pull request by shulard**
This is a famous CSS post processor: http://pleeease.io/

I've added it as a plugin and also added it inside the shared/Css.js compilation flow.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Why does this need to go in the core?

**Comment by shulard** [comment]
Maybe I'm wrong but I think it need to be in the compilation flow because it's just a post-processor... A task will request to generate a file and post-process it in another one...

For me it's exactly the same as Autoprefixer...

**Comment by taylorotwell** [comment]
I think you can probably write an extension for this.

**Comment by shulard** [comment]
Ok... Can you just give me some tips ? I already tried to create an extension for that but I haven't found a way to put it in the compilation flow...

I need to create a new flow specially for this ?

**Comment by mikeerickson** [comment]
@shulard You can use one of my elixir plugins as a starter 

https://github.com/mikeerickson/laravel-elixir-behat

**Comment by shulard** [comment]
Thanks for the link, I'll check that!

**Comment by JeffreyWay** [comment]
@mikeerickson's example is for Elixir 2. The extension syntax has changed. See the Laravel docs.

**Comment by mikeerickson** [comment]
@jeffreyway ah I missed this item? I will update plugin to bring it within compliance with Elixir 3.

**Pull request closed without merging**
