### PR TITLE
added browsersync

### PR DESCRIPTION
**Pull request by AndreasHeiberg**

### CODE REVIEW

**Comment by JeffreyWay** [comment]
Haven't used Browsersync in a while. Can you give me instructions for how to verify that this works?

**Comment by AndreasHeiberg** [comment]
On a standard homestead box:

- Replace `node_modules/laravel-elixir` with this version.

- Install new deps

```
cd node_modules/laravel-elixir
npm install
```
- Edit gulp.js:

```
elixir(function(mix) {
    mix.less('app.less');
    mix.browserSync();
});
```

- Run `gulp watch`
- Open [http://homestead.app:3001](http://homestead.app:3001) to see the BrowserSync UI
- Open [http://homestead.app:3000](http://homestead.app:3000) to see your app
- Add `body { background: red; }` to app.less
- Watch the glory that is BrowserSync haha

**Comment by JeffreyWay** [comment]
Thanks!

**Comment by AndreasHeiberg** [comment]
Added initial draft of documentation https://github.com/laravel/docs/pull/1821

**Comment by leek** [comment]
@AndreasHeiberg: Much appreciated! :+1:

Just wanted to share; I was able to make this a tad bit better by installing the [dotenv](https://github.com/motdotla/dotenv) package to read the `.env` file so that we don't have to hardcode the hostname for BrowserSync.

It would be nice if someone could get this into Laravel/Elixir by default. /cc @JeffreyWay 

```js
// gulpfile.js

require('dotenv').load();

var url    = require('url');
var elixir = require('laravel-elixir');

// Read APP_URL from .env and parse hostname
elixir.config.browserSync.proxy = url.parse(process.env.APP_URL).hostname || 'homestead.app';

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 */

elixir(function(mix) {
    mix.browserSync();
});
```

**Comment by AndreasHeiberg** [comment]
I don't know @JeffreyWay stance on using environment files for elixir, but I'm sure he will let you know.

Personally I don't really care for it, it's one more file to update to manage this very isolated system for assets. I like having gulp.js being the only source of truth, but thats just me.

One concern could be having multiple developers with different domains for the same project, but to that I only have to say, use the same domain. At any company I work at I'm definitely the camp that prefers standardizing setup like that company wide.

**Comment by leek** [comment]
@AndreasHeiberg: Multiple developers using different hostnames is exactly the issue I was dealing with. 

However, I just realized that the `APP_URL` key in `.env` was a custom addition - for some reason I thought it was a default key in the Laravel distribution. In that case, ignore my previous message :)

**Comment by AndreasHeiberg** [comment]
Oh yeah if it was default I would be inclined to agree.

**Pull request merged**
