### PR TITLE
Add minifier options to elixir config

### PR DESCRIPTION
**Pull request by nbourguig**
Hi,

Just a small commit adding the possibility to specify uglify options in elixir config.

This is helpful, if for instance we are using angular and we need to specify `{mangle: false} `.

### CODE REVIEW

**Comment by JeffreyWay** [comment]
Nobody else has requested this. So I'm inclined to not make it configurable. If a bunch of people ask about it, we can merge it at a later date. Thx!

**Comment by nbourguig** [comment]
OKay, too bad though.

**Comment by tymondesigns** [comment]
Why would you need to set mangle to false?

If it's because it messes with angular's dependency injection, then you just need to add ng-annotate to your build process

**Comment by nbourguig** [comment]
Yes, it is the main reason.

I didn't have much luck using ng-annotate. I will give it another try. 
Thx.

**Comment by muratsplat** [comment]
@tymondesigns How to use ng-annotate with elixir?  I'm writing a angular app using  ECS6 Class and  while my app  is minifying it get error about module injecting..

**Comment by muratsplat** [comment]
Finally I was created my Elixir task to avoid  Dependency Injection  using Angular App on browser...

https://gist.github.com/muratsplat/db1cc9b98e1d8cd27e48

**Pull request closed without merging**
