### PR TITLE
Added ability to change public directory

### PR DESCRIPTION
**Pull request by Marwelln**
If you didn't use `public` as public directory, version would fail, no matter what because it was hard coded. This change will allow you to change it.

If you are using `public_html` instead of `public`, you can with this change use

    .version('css/app.css', 'public_html', 'public_html');

This will set the base path to `public_html` (third argument). Second argument would tell the build directory to be `public_html/build`.

### CODE REVIEW

**Comment by dandonahoe** [comment]
This has been driving me crazy as well

**Comment by JeffreyWay** [comment]
But why would it ever be public_html? Laravel uses the public/ folder.

Sorry if I'm misunderstanding something... Will close unless someone responds with more clarification.

**Comment by Marwelln** [comment]
Because not all webhosts uses `public` as their public folder. It's possible to change the public directory in Laravel so it would be weird not being able to change it in Elixir that ships with Laravel.

Elixir can be used outside of Laravel too, and it's the same there, not everyone uses `public` as their public directory.

**Comment by kirkbushell** [comment]
+1

**Comment by JulienTant** [comment]
+1

And, this is such a nice feature for poeple using it outside Laravel, or even inside Laravel if they don't use public for any reasons.

**Comment by nWidart** [comment]
+1
It seems logical that if laravel gives the option to rename the Public folder, that Elixir should do too.

**Comment by patrickbrouwers** [comment]
+ 1 
Our VPS's use DirectAdmin and have public_html set as default. It's not really easy to change it every time. We would rather change a config setting in Elixir, so we can use features like cache busting properly.
I don't see any harm in having a setting for the publicPath (in elixir.json), which is set to `public` by default.

**Comment by FrankPeters** [comment]
+1 

I agree with the arguments mentioned above, would like this as well. :+1:

**Pull request closed without merging**
