### PR TITLE
add support for browserlist in autoprefixer

### PR DESCRIPTION
**Pull request by bdreesen**
I had a use case where i had to support an older version of Firefox. 
Elixir by default, strips out  -moz-box-sizing from the bootstrap source.
This breaks the layout and no way to override the autoprefixer as to my knowledge.

Uses default when nothing is specified.
```
> 1%, last 2 versions, Firefox ESR, Opera 12.1
```

override in config.js or elixir.json
```javascript
var config = {
  ...
  browserlist: {
    browsers: [ '> 1%', 'last 2 versions', 'Firefox >= 20', 'Opera 12.1' ]
  },
  ...
}
```

### CODE REVIEW

**Comment by JeffreyWay** [comment]
I'm just not convinced we need this configurable...

I'd rather find a better default that makes everyone happy.

**Comment by juukie** [comment]
If it ain't much work to make it configurable I would prefer it being configurable. Losing the ability to set options/config in plugins used by Elixir is one of the things that is holding me back to use it.

**Comment by tymondesigns** [comment]
I personally think this should be configurable in one way or another. Since we all have different requirements as to what browsers need to be supported, as dictated by a business or other.

**Comment by loranger** [comment]
Being able to simply lower or not the prefixes is really important to me too.

Making autoprefixer configurable allows everyone to use the default elixir configuration, while targetting explicitely some old or new browsers depending on the project you are working on would be allowed too.

Please @JeffreyWay let us use elixir in a simple elegant way instead of creating our duplicated gulp tasks in order to use autoprefixer the way we need it.
Dealing with those browser specificities is already a pain in the ass, we need support, here.

**Comment by nhowell** [comment]
@JeffreyWay Please reconsider. Yes, it's good to have a sensible default for most users, but other factors (business decisions or otherwise) force some of us to support older browsers. This PR would make doing so simple.

**Comment by awells-db** [comment]
@JeffreyWay +1 for making this configurable; a good default setting is great but would like to be able to set this in the config

**Comment by JeffreyWay** [comment]
This was added a while pack.

https://github.com/laravel/elixir/blob/master/src/Config.js#L179-L187

**Pull request closed without merging**
