### PR TITLE
Added config.publicDir, removed hardcode in version.js

### PR DESCRIPTION
**Pull request by edpelesh**
Removed hardcoded path to ‘public’ folder as it is not always named this way. We can change our cssOutput or jsOutput but it breaks version.js because of predefined base path in the task.

### CODE REVIEW

**Comment by mikeerickson** [comment]
I have been meaning to fork this project and make these types of settings into a Config object that would be used package wide and fix issues such as this 

Any interest, or would it be a waste of time and energy for the masses.

**Comment by edpelesh** [comment]
Well, it is present if I understood you correctly. Right now elixir.config is available and it gets further extended by elixir.json properties (if the latter file exists). Or maybe you have better ideas?

**Comment by IsraelOrtuno** [comment]
:+1: I've just been dealing with this

**Comment by josvar** [comment]
+1 I've also been deaing with this.

**Comment by edpelesh** [comment]
Holy sh*t. Looks like it's already proposed at pull request #43. Not sure why @JeffreyWay is so passive on merging this fix. Hope this duplicate helps :)

Feel free to close this as duplicate when seen ;P

**Comment by JeffreyWay** [comment]
I'm trying to figure out in what situation it *wouldn't* be the public directory. 

You'd always use Elixir in development, where the folder is "public." Clarification please?

**Comment by IsraelOrtuno** [comment]
The folder might not be "public" as Laravel allows to change that folder

```
$app->bind('path.public', function ()
{
    return base_path() . '/public_html';
});
```

Is not my case, but in the #laravel-es channel I've seen many users that need to use for instance `public_html`

**Comment by JeffreyWay** [comment]
So this only makes sense for a very tiny percentage of Laravel users, who are with shared hosts and have no choice but to change the public folder name?

Hmm - just not convinced this needs to be configurable. I'll think on it. I'm working on some Elixir stuff this week, so we'll see.

**Comment by IsraelOrtuno** [comment]
Anyway, leaving it "public" by default and just let the user change it if needed would be a good option ;D

@JeffreyWay what I really would love is that version do not destroy the entire build file, I cannot copy fonts or whatever to that folder as everything gets deleted. I think this has been discussed in laracasts forum.

**Comment by edpelesh** [comment]
First of all it is possible to configure cssOutput and jsOutput dirs in elixir.json with the parent "public" folder. I thought it would be easy to configure both options to use "static" folder (which is a reserved folder for our production environment, but that's another story) and when I tried to version my css and js - it didn't work. Guess what - "public" was hardcoded in version.js ingredient. Solution here (at least as I see it) is to either let users set their public dir in config or to remove css and js folders from config to prevent this ambiguous situation. Then the users who want this "advanced" behaviour of custom public dir will be just forced to use pure gulp approach which is fine. I think elixir should be either configurable or fully integrated build only for standard laravel installation. Now it's something inbetween.

**Comment by patrickbrouwers** [comment]
Ran into the same problem.
Described it here as well: https://github.com/laravel/elixir/pull/35#issuecomment-79093874

+1 for this solution!

**Comment by patrickbrouwers** [comment]
@JeffreyWay Any reason this get's ignored?

**Pull request closed without merging**
