### PR TITLE
Allow override baseDir in less and sass

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
Close issue #593

### CODE REVIEW

**Comment by randohinn** [comment]
@JeffreyWay @taylorotwell  Could we please get a merge for this soon? And onto npm aswell. A work blocker for me..

**Comment by JeffreyWay** [comment]
This is a breaking change, so I have to think about it a bit.

@randohinn - This shouldn't be a work blocker for you. You can begin any path with ./ to change the default base dir.

**Comment by randohinn** [comment]
Hmm, go figure. I swear `./` bailed on me the last time i tried it. Works for now, thanks.

 The way the docs are written, suggests that the only options for doing anything with the directories is either using `resources/assets/***/` or the `baseDir` argument anyways. The only 2 mentions of  `./` are in the **Writing Elixir Extensions** part. Should be a bit more clearly stated that  `./` works too, relative to the current directory. From  what can be read now, `./`might very well resolve to `resources/assets/`.

**Comment by cmosguy** [comment]
@JeffreyWay are you going to merge this, supposedly this fixes the issue that I am referring to in: https://github.com/laravel/elixir/issues/297

**Comment by cmosguy** [comment]
@jeffreyway hope I am not being too much of a PITA, but I installed your latest release and the gulp watch on my sass directory did not work. Is this working for you?

**Comment by JeffreyWay** [comment]
@cmosguy - Yeah, it has always worked on my end. I just installed from scratch and tried watching Sass files from a custom base directory.

```
mix.sass('app.scss', null, './app/assets');
```

It all watched properly.

If it's not working for you - sorry if you've already given this information elsewhere - but send me:

1. Your OS
2. Your installed version of Elixir. You said 6.0.0-10, right?
3. If you're using any VM at all.

Very strange - but we'll figure it out! :)

**Comment by cmosguy** [comment]
Hey @JeffreyWay 

Thanks for your help.  I did two tests using `laravel-elixir 6.0.0-10`:

1. Windows 7 host machine doing `gulp watch` then edit my `*.scss` files, no compiling updates worked.
1. Create VM using latest Laravel Homestead.  Ran `gulp watch` still  no compilation.  

Conclusion: watch auto compile mechanism does not work on either type of OS: Windows 7 or Ubuntu.

Here is my test case you can use to reproduce the problem:
```bash
git clone git@github.com:cmosguy/laravel-elixir-sass-watch-testcase.git
cd laravel-elixir-sass-watch-testcase
npm install
gulp watch
```
Then try to edit `sass/style.scss` or any other file in that directory tree.  No automatic compilation seems to work.

Thanks again for your support with this!

**Comment by ricardogobbosouza** [comment]
This is happening because you are passing an array in src and being an array as it assumes baseDir the prefix in your case was not passed, or is being watched all the files in the default setting `resources/assets/sass/**/*.+(sass|scss)`

Your gulpfile:
```
elixir(function (mix) {
    mix.sass(['./sass/style.scss'], '../style.css');
});
```

Try this:
```
elixir(function (mix) {
    mix.sass('./sass/style.scss', '../style.css');
});
```

Or:
```
elixir(function (mix) {
    mix.sass(['style.scss'], '../style.css', './sass/');
});
```

The third parameter is the BASEDIR after this merge!

Thanks

**Comment by cmosguy** [comment]
@ricardogobbosouza I just tried your idea!  It worked!

@JeffreyWay I think the take-away here is that it is really easy for one to break the watch functionality if you are not using arrays [] or just pure strings. This is confusing, and it would be great if there were a message or some more intelligence built in as I do believe one could easily break this by putting simple arrays.

I would thing a simple array should still work here.

Thanks again @ricardogobbosouza !

**Pull request merged**
