### PR TITLE
configurable "runAllTasks()" before watch

### PR DESCRIPTION
**Pull request by StefanoMagrassi**
It was added a configuration to enable/disable `runAllTasks()` call before watch.

This should help in some cases when `gulp watch` fails because of watchers start before all tasks are finished.

It is like a hack, but it can be useful. I think that to fix all the issues related to `watch`

### CODE REVIEW

**Comment by lukepolo** [comment]
If this works , im going to be a very very happy person

**Comment by JeffreyWay** [comment]
Can you help me understand better the issue that you're fixing here? 

So, if `gulp watch` triggers all tasks, it's possible in some cases that the watchers will start before they've completed? Is that what you're saying?

If that's so, can we fix it without a hack? Or maybe we can disable runAllTasks() entirely. That's how Elixir used to behave.

**Comment by StefanoMagrassi** [comment]
@JeffreyWay yes, this is the problem. Or at least it seems that it happens in my last project (a lot of less and browserify compilation).

I thought that adding a configuration in order to enable/disable `runAllTasks()` could be more flexible and less destructive.

**Comment by StefanoMagrassi** [comment]
@JeffreyWay anyway IMHO `watch` shouldn't run all the tasks before start: this should be done by the developer if it helps him, maybe with some npm scripts.

**Comment by JeffreyWay** [comment]
Okay, then I'm going to close this PR and remove that section.

**Comment by JeffreyWay** [comment]
Actually, changed my mind. We're still triggering all tasks on `gulp watch`, but I think the commit I just made should ensure that those watchers aren't added until all tasks have completed.

**Comment by StefanoMagrassi** [comment]
@JeffreyWay ok, this should work fine, but there still are a couple of changes that can be done to make the code better.
I will send you another PR

**Comment by StefanoMagrassi** [comment]
@JeffreyWay sadly your change doesn't work... I think that your approach is correct, but maybe the problem stands at a lower level.

It seems that the "guilty" task is `version`: when gulp runs `default` the log says that task is finished after *n* milliseconds and it starts `watch`, but actually `default` is still running because the versioned files are added to the build directory after a couple of seconds.

**Comment by lukepolo** [comment]
ideas on  how to fix this?

**Comment by TechyTimo** [comment]
@JeffreyWay Check my temporary solution on #626 . It works every time. It may bring up some ideas.

**Pull request closed without merging**
