### PR TITLE
Allow baseDir to be changed

### PR DESCRIPTION
**Pull request by antonioribeiro**

### CODE REVIEW

**Comment by JeffreyWay** [comment]
If we did this, it would need to be done across the board for Sass, Less, etc. Otherwise, it would be too inconsistent.

But, generally, the recommended way is to either do:

```
mix.sass('./some/other/base/path/file.scss')`
```

Or to updated the config property for your assets directory.

```
elixir.config.assetsPath = './app/assets';
```

Not against adding this, if the options above don't make sense for you?

**Comment by antonioribeiro** [comment]
As a matter of fact, it's only missing on some, it already works (at least) for Styles, Scripts, Babel, Browserify, so this baseDir option is a bit inconsistent at the moment.

And unfortunately assetsPath doesn't work for me because in this project I have 2 different assets base dirs:

public/templates/templateDir
public/assets/vendor/bower/

But I'm not really sure I'm doing things the way I should, so here's my gulpfile and a 'delete' extension I had to create:

```
var deleteExtension = './vendor/pragmarx/sdk/src/elixir/extensions/delete.js';

var elixir = require(deleteExtension).getElixir();

var paths = {
    'root': './',
    'resourcesAssets': 'resources/assets/',
    'publicAssets':  'public/assets/',
    'jquery': 'public/assets/vendor/bower/jquery/',
    'jqueryMigrate': 'public/templates/seantheme.com/color-admin-v1.9/admin/html/assets/plugins/jquery/',
    'jqueryUi': 'public/assets/vendor/bower/jquery-ui/',
    'bootstrap': 'public/assets/vendor/bower/bootstrap/dist/',
    'jquerySlimscroll': 'public/assets/vendor/bower/jquery-slimscroll/',
    'jqueryCookie': 'public/assets/vendor/bower/jquery.cookie/',
    'jvectormap': 'public/templates/seantheme.com/color-admin-v1.9/admin/html/assets/plugins/jquery-jvectormap/',
    'boostrapCalendar': 'public/templates/seantheme.com/color-admin-v1.9/admin/html/assets/plugins/bootstrap-calendar/',
    'jqueryGritter': 'public/assets/vendor/bower/jquery.gritter/',
    'seathemeDashboardV2': 'public/templates/seantheme.com/color-admin-v1.9/admin/html/assets/',
    'vue': '/public/assets/vendor/bower/vue/dist/',
    'vueResource': 'public/assets/vendor/bower/vue-resource/dist/',
    'datatables': 'public/assets/vendor/bower/datatables/media/',
    'datatablesButtons': 'public/templates/seantheme.com/color-admin-v1.9/admin/html/assets/plugins/DataTables/extensions/Buttons/',
    'datatablesResponsive': 'public/assets/vendor/bower/datatables-responsive/',
    'seanthemeApp': 'public/templates/seantheme.com/color-admin-v1.9/admin/html/assets/',
    'seanthemePace': 'public/templates/seantheme.com/color-admin-v1.9/admin/html/assets/plugins/pace/',
    'seanthemeOnePage': 'public/templates/seantheme.com/color-admin-v1.9/one-page-parallax/assets/',
    'fontAwesome': 'public/assets/vendor/bower/font-awesome/',
    'animateCss': 'public/assets/vendor/bower/animate.css/',
    'scrollMonitor': 'public/templates/seantheme.com/color-admin-v1.9/one-page-parallax/assets/plugins/scrollMonitor/',
}

var files = {
    'mainCss': paths.publicAssets + 'css/main.css',
    'mainJs': paths.publicAssets + 'js/main.js',
    'sassCompiled': paths.publicAssets + 'css/sass-compiled.css',
    'babelCompiled': paths.publicAssets + 'js/babel-compiled.js',
    'preloadJs': paths.publicAssets + 'js/preload.js',
    'onepageCss': paths.publicAssets + 'css/onepage.css',
    'onepageJs': paths.publicAssets + 'js/onepage.js',
}

elixir(function(mix) {
    mix
        .sass([
            paths.datatablesResponsive + "css/responsive.bootstrap.scss",
            paths.resourcesAssets + "sass/main.scss",
        ], files.sassCompiled, null, paths.root)

        .styles([
            paths.jqueryUi + "themes/base/minified/jquery-ui.min.css",
            paths.bootstrap + "css/bootstrap.css",
            paths.fontAwesome + "css/font-awesome.css",
            paths.animateCss + "animate.css",
            paths.seanthemeApp + "css/style.min.css",
            paths.seanthemeApp + "css/style-responsive.min.css",
            paths.seanthemeApp + "css/theme/default.css",
            paths.jvectormap + "jquery-jvectormap-1.2.2.css",
            paths.boostrapCalendar + "css/bootstrap_calendar.css",
            paths.jqueryGritter + "css/jquery.gritter.css",
            paths.seanthemeApp + "css/red.css",
            paths.datatables + "css/dataTables.bootstrap.min.css",
            paths.datatablesButtons + "css/buttons.bootstrap.min.css",
            files.sassCompiled,
        ], files.mainCss, paths.root)

        .babel([
            paths.resourcesAssets + "js/dashboard/components.js",
            paths.resourcesAssets + "js/dashboard/app.js",

            paths.resourcesAssets + "js/chat/components.js",
            paths.resourcesAssets + "js/chat/app.js",
        ], files.babelCompiled, paths.root)

        .scripts([
            paths.jquery + "jquery.js",
            paths.jqueryMigrate + "jquery-migrate-1.1.0.min.js",
            paths.jqueryUi + "ui/jquery-ui.js",
            paths.bootstrap + "js/bootstrap.js",
            paths.jquerySlimscroll + "jquery.slimscroll.js",
            paths.jqueryCookie + "jquery.cookie.js",
            paths.jvectormap + "jquery-jvectormap-1.2.2.min.js",
            paths.jvectormap + "jquery-jvectormap-world-merc-en.js",
            paths.boostrapCalendar + "js/bootstrap_calendar.min.js",
            paths.jqueryGritter + "js/jquery.gritter.js",
            paths.seathemeDashboardV2 + "js/dashboard-v2.min.js",
            paths.resourcesAssets + "js/socket.io.min.js",
            paths.datatables + "js/jquery.dataTables.js",
            paths.datatables + "js/dataTables.bootstrap.js",
            paths.datatablesButtons + "js/dataTables.buttons.min.js",
            paths.datatablesButtons + "js/buttons.bootstrap.min.js",
            paths.datatablesButtons + "js/buttons.print.min.js",
            paths.datatablesButtons + "js/buttons.flash.min.js",
            paths.datatablesButtons + "js/buttons.html5.min.js",
            paths.datatablesResponsive + "js/dataTables.responsive.js",
            paths.scrollMonitor + "scrollMonitor.js",

            paths.seanthemeApp + "js/apps.min.js",  /// --------- must be last
            files.babelCompiled,
        ], files.mainJs, paths.root)

        .scripts([
            paths.vue + "vue.js",
            paths.vueResource + "vue-resource.js",
            paths.seanthemePace + "pace.min.js"
        ], files.preloadJs, paths.root)

        // One Page

        .styles([
            paths.bootstrap + "css/bootstrap.css",
            paths.fontAwesome + "css/font-awesome.css",
            paths.animateCss + "animate.css",
            paths.seanthemeOnePage + "css/animate.min.css",
            paths.seanthemeOnePage + "css/theme/default.css",
            paths.seanthemeOnePage + "css/theme/red.css",
            //paths.seanthemeOnePage + "css/style.min.css", THOSE TWO ARE NOT WORKING WHEN COMPILING!
            //paths.seanthemeOnePage + "css/style-responsive.min.css",
        ], files.onepageCss, paths.root)

        .scripts([
            paths.jquery + "jquery.js",
            paths.jqueryMigrate + "jquery-migrate-1.1.0.min.js",
            paths.jqueryUi + "ui/jquery-ui.js",
            paths.bootstrap + "js/bootstrap.js",
            paths.jqueryCookie + "jquery.cookie.js",
            paths.scrollMonitor + "scrollMonitor.js",
            paths.seanthemeOnePage + "js/apps.min.js", /// must be last
        ], files.onepageJs, paths.root)

        .copy(paths.fontAwesome + 'fonts', paths.publicAssets + 'fonts')

        .delete([
            files.babelCompiled,
            files.sassCompiled,
            paths.publicAssets + 'css/*.map',
            paths.publicAssets + 'js/*.map',
        ])

        .version([
            files.mainCss,
            files.mainJs,
            files.preloadJs,
            files.onepageCss,
            files.onepageJs,
        ])
    ;
});
```

The extension

```
var elixir = require('laravel-elixir');
var del = require('del');

elixir.extend('delete', function(src)
{
    new elixir.Task('delete', function()
    {
        elixir.Log
            .heading("Deleting files...")
            .files(src, true);

        return del(src);
    });
});

exports.getElixir = function() {
    return elixir;
};
```

**Comment by antonioribeiro** [comment]
Looks like we only need to add it for Cofee, Sass and Less, so, done.

**Comment by JeffreyWay** [comment]
Have decided to keep the API simpler and not do this. May even remove the current base directory task options in a future release. Thanks!

**Pull request closed without merging**
