### PR TITLE
Add configuration for notifications.

### PR DESCRIPTION
**Pull request by willvincent**

### CODE REVIEW

**Comment by JeffreyWay** [comment]
I'm thinking it would be easier to have a single config property/flag to turn all notifications on or off.

**Comment by willvincent** [comment]
It would be simpler, yes.  But this gives the flexibility of having only failed tests and errors to show notifications, for example.

**Comment by JeffreyWay** [comment]
But if somebody wants to completely disable notifications, does this PR assume that they must override four different config properties?

**Comment by willvincent** [comment]
It does.  Maybe it should just be a string, that way it could have an option of 'all' to disable all notifications, or allow a list of options for specific notification types to disable.

**Comment by jfoliveira** [comment]
I've just upgrades Elixir from 2 to 3.2.8.
To disable notifications, I had this in my gulpfile:
```node
process.env.DISABLE_NOTIFIER = elixir.config.production;
```
This worked like a charm in Elixir 2, but no longer works after upgrade to 3.2.8.
I also tried:
```node
elixir.config.notifications.message = !elixir.config.production;
elixir.config.notifications = !elixir.config.production;
process.env.DISABLE_NOTIFIER = elixir.config.production;
```
None of these options work now.
Would you please give an example on how to disable notifications in 3.2.8?

**Pull request closed without merging**
