### PR TITLE
Switched from minifyCss to cssnano

### LINKED ISSUE #396: gulp-minify-css is deprecated
During installation npm says:
`npm WARN deprecated gulp-minify-css@1.2.3: Please use gulp-cssnano instead.`

### PR DESCRIPTION
**Pull request by zupolgec**
Since minifyCss has been deprecated, I've switched to cssnano (as suggested by the deprecation message).

Fixes #396

### CODE REVIEW

**Comment by JeffreyWay** [comment]
Thanks!

**Comment by schystz** [comment]
Hi, noob question, how do I get this update? I'm using `"laravel-elixir": "^4.0.0",` on my package.json file but still getting the warning. Tia!

**Comment by zupolgec** [comment]
@schystz Jeffrey has bumped the version to 4.2.0, now it should update

**Comment by schystz** [comment]
Yup that solves it thanks!

**Pull request merged**
