### PR TITLE
Allow that versioned files are created next to the source file.

### PR DESCRIPTION
**Pull request by isaacperaza**
This tittle change allow to created versioned file next to source file, just if assestPath and buildFolder have the same value.

I tested this change overriding assetsPath and buildFolder values from gulpfile.js, elixir.json and specifying a second parameter of mix.version([files], "public" ) task, please take a look:

Overriding elixir configuration from gulpfile.js:

```javascript
// Load Laravel elixir
var Elixir = require('laravel-elixir');

// Get elixir configuration
var config = Elixir.config;

// Overwrite assetPath
config.assetsPath = 'public';

// Overwrite buildFolder
config.versioning.buildFolder = '';

Elixir(function(mix) {
    mix.version([
        // replace css files path with yours
        config.assetsPath + '/css/user.css',
        config.assetsPath + '/css/contact.css',

        // replace script files path with yours
        config.assetsPath + '/js/user.js',
        config.assetsPath + '/js/contact.js'
    ]);
});
```

Overriding elixir configuration from gulpfile.js second option:

```javascript
...
// Overwrite assetPath
config.assetsPath = 'public';

Elixir(function(mix) {
    mix.version([
        // replace css files path with yours
        config.assetsPath + '/css/user.css',
        config.assetsPath + '/css/contact.css',

        // replace script files path with yours
        config.assetsPath + '/js/user.js',
        config.assetsPath + '/js/contact.js'
    ], 'public');
});
```

Overriding elixir configuration using elixir.json file:

```javascript
{
  "assetsPath": "public",

  "versioning": {
    "buildFolder": ""
  }
}
```

Output will looks like this:

```
public
└─ css
 └─ user.css
 └─ user-8fa778f76c.css
 └─ contact.css
 └─ contact-b45e8b679c.css
└─ js
 └─ user.js
 └─ user-676f8ea6c9.js
 └─ contact.js
 └─ contact-8e660751aa.js
└─ rev-manifest.json
  ```

Finally the rev-manifest.json file looks good as well:
```json
{
  "css/user.css": "css/user-8fa778f76c.css",
  "css/contact.css": "css/contact-b45e8b679c.css",
  "js/user.js": "js/user-676f8ea6c9.js",
  "js/contact.js": "js/contact-8e660751aa.js"
}
```

Please, let me know any doubts or concerns.

### CODE REVIEW

**Comment by Rjs37** [comment]
assetsPath is meant for the source location of the assets so you shouldn't be using that. It caused issues for me when using the other commands such as sass.

publicPath is probably the right config to check against and by default it is already set to the right directory. Once I put that in instead it worked great for me.

It also means that `'public/assets/img'` instead of `'public/assets/img/**/*.*'`

**Comment by JeffreyWay** [comment]
Yeah - I think you want publicPath here. Can you update?

**Comment by JeffreyWay** [comment]
Actually, this would break code I believe. Also Laravel core's `elixir()` function. So my instinct is to keep things the way they are.

**Comment by Rjs37** [comment]
Once that error is corrected it shouldn't break anything? The main benefit of this change is that it fixes the issues that occur when using the same folder for public and versioned assets.
* The original unversioned files are now kept rather than deleted (due to the del command on the build folder)
* The filtering doesn't need to be as specific i.e. `/img` can be used rather than `/img/**/*.*`

Laravel core's elixir() function has a manually defined build directory but there's nothing stopping us from overriding that behavior. This change shouldn't introduce any issues, only fix a couple that already exist.

**Comment by isaacperaza** [comment]
Sorry guys, I had to work all weekend, but you are totally right ( @JeffreyWay, @Rjs37 ), I have to use publicPath instead of assetPath. 

@JeffreyWay Laravel Elixir is totally awesome, thanks for that, but for some legacy applications that are migrating to Laravel the suggested change will be awesome, maybe for a small application/web site is not a big deal, but for a large application change the assets path will be a big deal an risk.

I going to apply your suggestions and I think @Rjs37 will help me to test that all is working fine.

Please let us know your concerns and we can deal with them as well.

**Comment by Rjs37** [comment]
@isaacperaza are you going to make that change? At the moment I'm working with the change made directly to the local copy of elixir, so it'd be good to get this fixed and then pulled into the main repo :).

@JeffreyWay What did you think this change would break? (after the quick fix has been made)

**Pull request closed without merging**
