### PR TITLE
Sourcemaps support

### PR DESCRIPTION
**Pull request by morrislaptop**
Automatically turned on if not in production and be explicitly set via elixir.json

Works across LESS / SASS / Coffee and merging files

### CODE REVIEW

**Comment by JosephSilber** [comment]
Why would you turn off source maps in production?

One of the best things about source maps is that you can use them even in production, to debug your minified code.

**Comment by morrislaptop** [comment]
2 reasons:

1. File size / requests / server load - when you include a source map inline or the browser has to make another request (I know chrome doesn't load the map file unless dev tools is open, not sure about other browsers)

1. Protecting source code - You might not want to allow people to access your source code on a production site

However I'm not one to force my beliefs so you can easily turn sourcemaps on in production by creating `elixir.json` in your root and specifying:

```json
{
    "sourcemaps": true
}
```

**Comment by JeffreyWay** [comment]
I'm honestly not overly well-versed with sourcemaps. How do I test this out to make sure it works?

**Comment by JeffreyWay** [comment]
NM - I'll figure it out right now. Merging.

**Comment by JeffreyWay** [comment]
Okay, this seems to work well. I'm still not sure about the "disabled for production" thing. 

Like I said, I'm not well-versed in this area, but a few people seem to think that it's a non-issue. Can we get away with keeping it on for production?

**Comment by morrislaptop** [comment]
Initially it was a safeguard measure in order to protect source code accidentally going in production. 

For users that do transpiling with less/scss/coffee I think this makes perfect sense.

For users that are just concatenating and minifying, it makes less sense (and it is kind of ironic that when minification is on source maps is off by default). 

In the end I think it is better to have the safer option as people who know about source maps will go and look how to implement it.

**Comment by JosephSilber** [comment]
I will just chime in one more time saying that this doesn't make much sense to me.

When developing locally you should be using non-minified code. The whole point of source maps is to be able to debug code in production.

**Comment by JosephSilber** [comment]
Also, I'm not really sure how this is a "security concern". Source maps only works for when your source files are publicly available.

If your files are publicly available, not having a source map file won't protect anything.

**Comment by morrislaptop** [comment]
When developing locally and transpiling SASS, LESS or Coffee you are using "non-minified" code, however source maps allows you to see where it came from in the SASS, LESS or Coffee source code. 

By default gulp source maps includes the source code in the source maps as it "just works" and you don't have to have your source code publicly available. So it could be a security / IP concern if you accidentally upload source maps into production - https://www.npmjs.com/package/gulp-sourcemaps#write-options

**Comment by JosephSilber** [comment]
I see, but I don't think this is the industry standard (I might be wrong about this).

JS by its nature is public. While some people might feel a false sense of security by not having their "source code" available, JS is just as much source code as anything else.

I just think it should default to having it...

**Comment by morrislaptop** [comment]
JS might have been public a while ago simply because tools like coffee and gulp weren't around. The trend is definitely heading to "build" stages in web dev for performance and security reasons.

How would we handle the use case of having it on by default and supporting having it off for production? You would have to either keep changing a setting in your source code OR have a config variable like sourceMapsProduction? 

Not having it in production is simply a sensible default and can be changed via elixir.json.

**Comment by MartinTale** [comment]
When using .version in elixir the path to source map is incorrect and it tries to find the sourcemap in build directory instead of where it is created. Is there an option that I can change for it to create sourcemaps where versioned files are or change path to sourcemap at the end of "compiled" js file?

**Comment by morrislaptop** [comment]
Mmmm that doesn't really apply to source maps as it isn't changing the source code. I would recommend you adding another method to the chain to get the source map in the build directory as well...

```javascript
    imix.version(['js/main.js', 'css/app.css'])
           .copy('public/js/main.js.map', 'public/build/js/main.js.map')
           .copy('public/css/app.css.map', 'public/build/css/app.css.map');
```

**Comment by MartinTale** [comment]
Problem with this solution is that it only calls copy method on initial gulp call. When using gulp watch the build directory content will be cleared and maps won't be copied back in there.

**Comment by morrislaptop** [comment]
Hmmm I would suggest writing another gulp elixir task that watches for map
files and ensure they get copied across.

**Comment by barryvdh** [comment]
Before Elixir, I would usually create sourcemaps with the source inlined, so you don't need the map files. And for production, you minify it so the sourcemaps are removed anyways.

**Pull request merged**
